version: '3'
services:
  radio:
    depends_on:
      - minio1
      - minio2
      - minio3
    image: "minio/radio:edge"
    hostname: "radio"
    restart: always
    ports:
      - "9000:9000"
    command:
      - server
      - -c
      - /config.yml

  minio1:
    volumes:
      - "minio1:/data"
    image: "minio/minio:edge"
    command:
      - server
      - /data
    restart: always
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "TX8mIIOGC12QBMJ45F0Z"
      MINIO_SECRET_KEY: "9ule1ga5JMfMmQXCoEPNcM2jij"

  minio2:
    volumes:
      - "minio2:/data"
    image: "minio/minio:edge"
    command:
      - server
      - /data
    restart: always
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: "GX82IIOGC12QBMJ45F0Z"
      MINIO_SECRET_KEY: "9ux11ga5JMfMmQXCoEPNcM2jij"

  minio3:
    volumes:
      - "minio3:/data"
    image: "minio/minio:edge"
    command:
      - server
      - /data
    restart: always
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: "HX8KIIOGC12QBMJ45F0Z"
      MINIO_SECRET_KEY: "9ux41ga5JMfMmQXCoEPNcM2jij"

volumes:
  minio1:
  minio2:
  minio3:
